### PR TITLE
WIP: Cheat Sheets

### PR DESCRIPTION
**Pull request by kaseybon**

### CODE REVIEW

**Comment by catheraaine** [comment]
Looks good! 

Do they need <div> or <span> ?

**Comment by kaseybon** [comment]
`div` and `span` are the last two items under **Basic Tags**

**Comment by kaseybon** [comment]
Feedback from Daniel:
- [ ] explain the `attrs` for the `a` and `img` tags
- [ ] make note of self closing tags: `img`, `br`, and `hr`
- [ ] **if time:** show examples of output next to code examples

**Comment by catheraaine** [comment]
Ah! Yes, yes they are.

**Comment by catheraaine** [comment]
Feedback from Daniel:
- [x] explain the `attrs` for the `a` and `img` tags
- [x] make note of self closing tags: `img`, `br`, and `hr`
- [ ] ~~**if time:** show examples of output next to code examples~~

**Pull request merged**
