### PR TITLE
:bug: update agenda page to reflect updated agenda google doc

### PR DESCRIPTION
**Pull request by boomingbrake**
issue #17 

@kaseybon

### CODE REVIEW

**Comment by kaseybon** [comment]
:point_up: @meljeans here are the updates to the agenda page so far. Let us know if anything else needs changed.

**Comment by meljeans** [comment]
Looks good to me!

**Comment by kaseybon** [comment]
@meljeans do we need to move the design portion to before lunch?

screen shot 2016-02-16 at 9 29 28 am

**Comment by meljeans** [comment]
I _thought_ we decided to have it after lunch, but now I'm not quite sure what we finalized. @emilykggray - does this agenda look accurate to you?

**Comment by catheraaine** [comment]
Scheduling is no longer the same, so I'm just going to close.

**Pull request closed without merging**
